# create container docker debian buster 
FROM debian:buster

# upgrade, install package for the nginx and protocol TSL
RUN apt update
RUN apt upgrade
RUN apt install nginx -y
RUN apt install openssl -y
